config/routes.rb
Twitterbell::Application.routes.draw do
  resources :rings

end

app/models/arduino.rb
class Arduino
  def self.hello_world
    require 'serialport'

    puts 'started ruby code...'
    #params for serial port
    port_str = "/dev/tty.usbserial-A6004osT"  #may be different for you
    baud_rate = 9600
    data_bits = 8
    stop_bits = 1
    parity = SerialPort::NONE
    @@sp = SerialPort.new(port_str, baud_rate, data_bits, stop_bits, parity)

    # wait for connection
    sleep(1)

    print "How long for notes? "
    note_duration = $stdin.gets.chomp.to_f
    # note_duration = 0.05
  
    print "How long for rest between rib & bon? "
    ribbon_rest_duration = $stdin.gets.chomp.to_f
    # ribbon_rest_duration = 0.3

    print "How long for rest between bon & farm? "
    farm_rest_duration = $stdin.gets.chomp.to_f
    # farm_rest_duration = 0.6
    
    # voices = ['Agnes', 'Albert', 'Alex', 'Bad News', 'Bahh', 'Bells', 'Boing', 'Bruce', 'Bubbles', 'Cellos', 'Deranged', 'Fred', 'Good News', 'Hysterical', 'Junior', 'Kathy', 'Pipe Organ', 'Princess', 'Ralph', 'Trinoids', 'Vicki', 'Victoria', 'Whisper', 'Zarvox']
    
    # print "Which voice? "
    # voice = $stdin.gets.chomp
    voice = 'Vicki'    
    
    count = 0
    loop do
      print "Twitter handle? "
      twitter_handle = $stdin.gets.chomp
      twitterer = Twitter.user(twitter_handle)
      greeting = "#{twitterer.name} #{twitterer.location.blank? ? '' : 'from ' + twitterer.location} is at the Ribbon Farm door. #{twitterer.screen_name} #{twitterer.description}. It's #{Time.now.strftime('%I:%M%p') }."
      
      rib(note_duration)
      rest(ribbon_rest_duration)

      bon(note_duration)
      rest(farm_rest_duration)

      farm(note_duration)

      # `say -v #{voices[count % voices.length]} "#{greeting}"`
      `say -v #{voice} "#{greeting}"`

      count += 1

      rest(1)
    end

    # close serial data line
    @@sp.close
    
    puts '...ended ruby code'

  end
  
  def self.rest(duration)
    sleep(duration)
  end
  def self.rib(duration)
    @@sp.write("1")
    sleep(duration)
    @@sp.write("0")
  end
  def self.bon(duration)
    @@sp.write("2")
    sleep(duration)
    @@sp.write("0")
  end
  def self.farm(duration)
    @@sp.write("3")
    sleep(duration)
    @@sp.write("0")
  end
end

app/models/doorman.rb
class Doorman
  include GeoKit::Mappable
  
  def self.check
    Twitter.mentions.reverse.each do |mention|
      if mention.text =~ /ding\s*dong/i
        if mention.geo
          mention_location = Geokit::LatLng.normalize mention.geo.coordinates
          ribbon_farm_location = Geokit::LatLng.normalize [42.329481,-83.065838]
          if distance = mention_location.distance_to(ribbon_farm_location) < 0.25
            puts 'ding dong!'
          else
            puts 'too far away'
          end
        else
          puts 'no geo specified in tweet'
        end
        # TODO create a ring model to store the tweet id for each ring
        # use the last one to pass in as since_id for mentions method
        # pass tweet into Ring.create method
        # create method actual doe the ring
      else
        puts 'did not ding dong'
      end
    end
  end
end

  

app/models/ring.rb
class Ring < ActiveRecord::Base
  attr_accessible :twitter_user_id, :tweet_created_at, :tweet_id, :tweet_text, :lat, :lng
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/rings_controller.rb
class RingsController < ApplicationController
  def index
    @rings = Ring.all
  end

  def show
    @ring = Ring.find(params[:id])
  end

  def new
    @ring = Ring.new
  end

  def create
    @ring = Ring.new(params[:ring])
    if @ring.save
      redirect_to @ring, :notice => "Successfully created ring."
    else
      render :action => 'new'
    end
  end

  def edit
    @ring = Ring.find(params[:id])
  end

  def update
    @ring = Ring.find(params[:id])
    if @ring.update_attributes(params[:ring])
      redirect_to @ring, :notice  => "Successfully updated ring."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @ring = Ring.find(params[:id])
    @ring.destroy
    redirect_to rings_url, :notice => "Successfully destroyed ring."
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rings_helper.rb
module RingsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twitterbell</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/rings/_form.html.haml
= form_for @ring do |f|
  = f.error_messages
  %p
    = f.label :twitter_user_id
    %br
    = f.text_field :twitter_user_id
  %p
    = f.label :tweet_created_at
    %br
    = f.datetime_select :tweet_created_at
  %p
    = f.label :tweet_id
    %br
    = f.text_field :tweet_id
  %p
    = f.label :tweet_text
    %br
    = f.text_field :tweet_text
  %p
    = f.label :lat
    %br
    = f.text_field :lat
  %p
    = f.label :lng
    %br
    = f.text_field :lng
  %p
    = f.submit

app/views/rings/edit.html.haml
- title "Edit Ring"

= render 'form'

%p
  = link_to "Show", @ring
  |
  = link_to "View All", rings_path

app/views/rings/index.html.haml
- title "Rings"

%table
  %tr
    %th Twitter user
    %th Tweet created at
    %th Tweet
    %th Tweet text
    %th Lat
    %th Lng
  - for ring in @rings
    %tr
      %td= ring.twitter_user_id
      %td= ring.tweet_created_at
      %td= ring.tweet_id
      %td= ring.tweet_text
      %td= ring.lat
      %td= ring.lng
      %td= link_to 'Show', ring
      %td= link_to 'Edit', edit_ring_path(ring)
      %td= link_to 'Destroy', ring, :confirm => 'Are you sure?', :method => :delete

%p= link_to "New Ring", new_ring_path

app/views/rings/new.html.haml
- title "New Ring"

= render 'form'

%p= link_to "Back to List", rings_path

app/views/rings/show.html.haml
- title "Ring"

%p
  %strong Twitter User:
  = @ring.twitter_user_id
%p
  %strong Tweet Created At:
  = @ring.tweet_created_at
%p
  %strong Tweet:
  = @ring.tweet_id
%p
  %strong Tweet Text:
  = @ring.tweet_text
%p
  %strong Lat:
  = @ring.lat
%p
  %strong Lng:
  = @ring.lng

%p
  = link_to "Edit", edit_ring_path(@ring)
  |
  = link_to "Destroy", @ring, :confirm => 'Are you sure?', :method => :delete
  |
  = link_to "View All", rings_path